export type ExploreCatalogMode = 'anime' | 'non-anime';
export type ExploreTypeFilter = 'all' | 'movie' | 'show';

export const QUICK_TAGS_BY_MODE: Record<ExploreCatalogMode, string[]> = {
  anime: [
    'Action',
    'Isekai',
    'Adventure',
    'Comedy',
    'Drama',
    'Fantasy',
    'Romance',
    'Shounen',
  ],
  'non-anime': [
    'Action',
    'Adventure',
    'Comedy',
    'Crime',
    'Drama',
    'Family',
    'Thriller',
  ],
};

export const EXPECTED_TAGS_BY_MODE: Record<ExploreCatalogMode, readonly string[]> = {
  anime: [
    'Action',
    'Adventure',
    'Adult Cast',
    'Anthropomorphic',
    'Avant Garde',
    'Award Winning',
    'Boys Love',
    'CGDCT',
    'Childcare',
    'Comedy',
    'Combat Sports',
    'Crossdressing',
    'Delinquents',
    'Detective',
    'Drama',
    'Ecchi',
    'Educational',
    'Erotica',
    'Fantasy',
    'Gag Humor',
    'Girls Love',
    'Gore',
    'Gourmet',
    'Harem',
    'Hentai',
    'High Stakes Game',
    'Historical',
    'Horror',
    'Idols (Female)',
    'Idols (Male)',
    'Isekai',
    'Iyashikei',
    'Josei',
    'Kids',
    'Love Polygon',
    'Magical Sex Shift',
    'Mahou Shoujo',
    'Martial Arts',
    'Mecha',
    'Medical',
    'Military',
    'Music',
    'Mystery',
    'Mythology',
    'Organized Crime',
    'Otaku Culture',
    'Parody',
    'Performing Arts',
    'Pets',
    'Psychological',
    'Racing',
    'Reincarnation',
    'Reverse Harem',
    'Romance',
    'Romantic Subtext',
    'Samurai',
    'School',
    'Sci-Fi',
    'Seinen',
    'Showbiz',
    'Shoujo',
    'Shounen',
    'Slice of Life',
    'Space',
    'Sports',
    'Strategy Game',
    'Super Power',
    'Supernatural',
    'Survival',
    'Suspense',
    'Team Sports',
    'Time Travel',
    'Vampire',
    'Video Game',
    'Visual Arts',
    'Workplace',
  ],
  'non-anime': [
    'Action',
    'Action & Adventure',
    'Adventure',
    'Animation',
    'Comedy',
    'Crime',
    'Documentary',
    'Drama',
    'Family',
    'Fantasy',
    'History',
    'Horror',
    'Kids',
    'Music',
    'Mystery',
    'News',
    'Reality',
    'Romance',
    'Science Fiction',
    'Sci-Fi & Fantasy',
    'Soap',
    'Talk',
    'Thriller',
    'TV Movie',
    'War',
    'War & Politics',
    'Western',
  ],
};

export function defaultTagForMode(mode: ExploreCatalogMode): string {
  return QUICK_TAGS_BY_MODE[mode][0] ?? '';
}

export function providerLabelForMode(mode: ExploreCatalogMode): string {
  return mode === 'anime' ? 'Jikan' : 'TMDB';
}

export function isExploreCatalogMode(value: unknown): value is ExploreCatalogMode {
  return value === 'anime' || value === 'non-anime';
}

export function isExploreTypeFilter(value: unknown): value is ExploreTypeFilter {
  return value === 'all' || value === 'movie' || value === 'show';
}
