export interface HlsSessionStatsResponse {
  sessionId: string;
  mediaId: string;
  startedAt: string;
  ffmpegPath: string;
  videoEncoder: 'cpu' | 'nvidia';
  sourceFilePath: string;
  segmentSeconds: number;
  totalDurationSeconds: number;
  totalSegments: number;
  selectedAudioStreamIndex: number | null;
  maxVideoBitrateKbps: number;
  audioBitrateKbps: number;
  maxOutputHeight: number;
  keyFrameInterval: number;
  progressiveSourceId: string | null;
  readySegments: number;
  contiguousReadySegments: number;
  readyThroughSeconds: number;
  readyPercent: number;
  highestReadySegment: number | null;
  inflightSegments: number[];
  inflightCount: number;
  globalInflightCount: number;
  cpuInflightCount: number;
  maxGlobalInflightJobs: number;
  maxSessionInflightJobs: number;
  maxCpuInflightJobs: number;
  overloadRetryAfterSeconds: number;
  nextSegmentIndex: number | null;
  recoverableStartFailures: number;
}
